# ETL Food Service Data

ETL to transform food service data into a snowflake database.

In [1]:
import pandas as pd

In [2]:
data_local = pd.read_excel('../data/food_service_data.xlsx', sheet_name= 'vendas_loja')

data_local

,Data,Turno,Prato,Valor R$,Pago,à Pagar,Taxa,Frete
0,2020-07-30 00:00:00,Manhã,Liguiça Acebolada + Maionese,12,OK,-,-,2
1,2020-07-30 00:00:00,Manhã,Carne de Panela + Maionese,12,OK,-,-,-
2,2020-07-30 00:00:00,Manhã,Frango + Maionese,12,OK,-,-,2
3,2020-07-30 00:00:00,Manhã,Frango + Maionese,12,OK,-,-,-
4,2020-07-30 00:00:00,Noite,Frango + Maionese,12,OK,-,-,2
...,...,...,...,...,...,...,...,...
2178,2022-04-10 00:00:00,-,-,NaN,OK,NaN,NaN,NaN
2179,2022-04-11 00:00:00,-,-,NaN,OK,NaN,NaN,NaN
2180,2022-04-12 00:00:00,-,-,NaN,OK,NaN,NaN,NaN
2181,2022-04-13 00:00:00,-,-,NaN,OK,NaN,NaN,NaN
2182,2022-04-14 00:00:00,-,-,NaN,OK,NaN,NaN,NaN

## Pre processing data

A first look at date shows that there are some '-' values in the data. Lest's fix that, and do some other cleaning.

In [3]:
# Replacing all '-' values with NaN

data_local = data_local.replace('-', pd.NA)

data_local

,Data,Turno,Prato,Valor R$,Pago,à Pagar,Taxa,Frete
0,2020-07-30 00:00:00,Manhã,Liguiça Acebolada + Maionese,12,OK,NaN,NaN,2
1,2020-07-30 00:00:00,Manhã,Carne de Panela + Maionese,12,OK,NaN,NaN,<NA>
2,2020-07-30 00:00:00,Manhã,Frango + Maionese,12,OK,NaN,NaN,2
3,2020-07-30 00:00:00,Manhã,Frango + Maionese,12,OK,NaN,NaN,<NA>
4,2020-07-30 00:00:00,Noite,Frango + Maionese,12,OK,NaN,NaN,2
...,...,...,...,...,...,...,...,...
2178,2022-04-10 00:00:00,NaN,NaN,NaN,OK,NaN,NaN,NaN
2179,2022-04-11 00:00:00,NaN,NaN,NaN,OK,NaN,NaN,NaN
2180,2022-04-12 00:00:00,NaN,NaN,NaN,OK,NaN,NaN,NaN
2181,2022-04-13 00:00:00,NaN,NaN,NaN,OK,NaN,NaN,NaN
2182,2022-04-14 00:00:00,NaN,NaN,NaN,OK,NaN,NaN,NaN

In [4]:
# Removing all rows with NaN in 'Prato' column

data_local = data_local.dropna(subset=['Prato'])

data_local

,Data,Turno,Prato,Valor R$,Pago,à Pagar,Taxa,Frete
0,2020-07-30 00:00:00,Manhã,Liguiça Acebolada + Maionese,12,OK,<NA>,<NA>,2
1,2020-07-30 00:00:00,Manhã,Carne de Panela + Maionese,12,OK,<NA>,<NA>,<NA>
2,2020-07-30 00:00:00,Manhã,Frango + Maionese,12,OK,<NA>,<NA>,2
3,2020-07-30 00:00:00,Manhã,Frango + Maionese,12,OK,<NA>,<NA>,<NA>
4,2020-07-30 00:00:00,Noite,Frango + Maionese,12,OK,<NA>,<NA>,2
...,...,...,...,...,...,...,...,...
2012,2021-10-30 00:00:00,Manhã,parmê + fritas,18,OK,NaN,NaN,NaN
2013,2021-10-30 00:00:00,Manhã,2x parmê + fritas,36,OK,NaN,NaN,NaN
2014,2021-10-31 00:00:00,<NA>,IBMH,88,OK,NaN,NaN,NaN
2016,2021-10-31 00:00:00,Manhã,só parmê + fritas,20,OK,NaN,NaN,NaN
2017,2021-11-01 00:00:00,<NA>,IBMH,NaN,OK,NaN,NaN,NaN

In [5]:
# Removing rows with NaN in 'Turno' column

data_local = data_local.dropna(subset=['Turno'])

data_local

,Data,Turno,Prato,Valor R$,Pago,à Pagar,Taxa,Frete
0,2020-07-30 00:00:00,Manhã,Liguiça Acebolada + Maionese,12,OK,<NA>,<NA>,2
1,2020-07-30 00:00:00,Manhã,Carne de Panela + Maionese,12,OK,<NA>,<NA>,<NA>
2,2020-07-30 00:00:00,Manhã,Frango + Maionese,12,OK,<NA>,<NA>,2
3,2020-07-30 00:00:00,Manhã,Frango + Maionese,12,OK,<NA>,<NA>,<NA>
4,2020-07-30 00:00:00,Noite,Frango + Maionese,12,OK,<NA>,<NA>,2
...,...,...,...,...,...,...,...,...
2008,2021-10-29 00:00:00,Manhã,strogonoff + batatinha palha,18,OK,NaN,NaN,NaN
2009,2021-10-29 00:00:00,Manhã,carne moída + legumes + guaracamp,20,OK,NaN,NaN,NaN
2012,2021-10-30 00:00:00,Manhã,parmê + fritas,18,OK,NaN,NaN,NaN
2013,2021-10-30 00:00:00,Manhã,2x parmê + fritas,36,OK,NaN,NaN,NaN
2016,2021-10-31 00:00:00,Manhã,só parmê + fritas,20,OK,NaN,NaN,NaN

In [6]:
# Replacing NaN values in 'Valor R$', 'à Pagar', 'Taxa', 'Frete' columns with 0

data_local['Valor R$'] = data_local['Valor R$'].fillna(0)
data_local['à Pagar'] = data_local['à Pagar'].fillna(0)
data_local['Taxa'] = data_local['Taxa'].fillna(0)
data_local['Frete'] = data_local['Frete'].fillna(0)

data_local

C:\Users\pedro\AppData\Local\Temp\ipykernel_49192\89203958.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_local['Valor R$'] = data_local['Valor R$'].fillna(0)
C:\Users\pedro\AppData\Local\Temp\ipykernel_49192\89203958.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_local['à Pagar'] = data_local['à Pagar'].fillna(0)
C:\Users\pedro\AppData\Local\Temp\ipykernel_49192\89203958.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_local['Taxa'] = data_local['Taxa'].fillna(0)
C:\Users\pedro\AppData\Local\Temp\ipykernel_49192\89203958.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_local['Frete'] = data_local['Frete'].fillna(0)

,Data,Turno,Prato,Valor R$,Pago,à Pagar,Taxa,Frete
0,2020-07-30 00:00:00,Manhã,Liguiça Acebolada + Maionese,12,OK,0.0,0.0,2.0
1,2020-07-30 00:00:00,Manhã,Carne de Panela + Maionese,12,OK,0.0,0.0,0.0
2,2020-07-30 00:00:00,Manhã,Frango + Maionese,12,OK,0.0,0.0,2.0
3,2020-07-30 00:00:00,Manhã,Frango + Maionese,12,OK,0.0,0.0,0.0
4,2020-07-30 00:00:00,Noite,Frango + Maionese,12,OK,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...
2008,2021-10-29 00:00:00,Manhã,strogonoff + batatinha palha,18,OK,0.0,0.0,0.0
2009,2021-10-29 00:00:00,Manhã,carne moída + legumes + guaracamp,20,OK,0.0,0.0,0.0
2012,2021-10-30 00:00:00,Manhã,parmê + fritas,18,OK,0.0,0.0,0.0
2013,2021-10-30 00:00:00,Manhã,2x parmê + fritas,36,OK,0.0,0.0,0.0
2016,2021-10-31 00:00:00,Manhã,só parmê + fritas,20,OK,0.0,0.0,0.0

In [7]:
# Replacing 'OK' values in 'pedido_pago' column with 1, and other values with 0

data_local['Pago'] = data_local['Pago'].replace('OK', 1)
data_local['Pago'] = data_local['Pago'].replace(pd.NA, 0)

data_local

C:\Users\pedro\AppData\Local\Temp\ipykernel_49192\1066630201.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_local['Pago'] = data_local['Pago'].replace('OK', 1)
C:\Users\pedro\AppData\Local\Temp\ipykernel_49192\1066630201.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_local['Pago'] = data_local['Pago'].replace(pd.NA, 0)

,Data,Turno,Prato,Valor R$,Pago,à Pagar,Taxa,Frete
0,2020-07-30 00:00:00,Manhã,Liguiça Acebolada + Maionese,12,1.0,0.0,0.0,2.0
1,2020-07-30 00:00:00,Manhã,Carne de Panela + Maionese,12,1.0,0.0,0.0,0.0
2,2020-07-30 00:00:00,Manhã,Frango + Maionese,12,1.0,0.0,0.0,2.0
3,2020-07-30 00:00:00,Manhã,Frango + Maionese,12,1.0,0.0,0.0,0.0
4,2020-07-30 00:00:00,Noite,Frango + Maionese,12,1.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...
2008,2021-10-29 00:00:00,Manhã,strogonoff + batatinha palha,18,1.0,0.0,0.0,0.0
2009,2021-10-29 00:00:00,Manhã,carne moída + legumes + guaracamp,20,1.0,0.0,0.0,0.0
2012,2021-10-30 00:00:00,Manhã,parmê + fritas,18,1.0,0.0,0.0,0.0
2013,2021-10-30 00:00:00,Manhã,2x parmê + fritas,36,1.0,0.0,0.0,0.0
2016,2021-10-31 00:00:00,Manhã,só parmê + fritas,20,1.0,0.0,0.0,0.0

In [8]:
# change data types

data_local['Data'] = pd.to_datetime(data_local['Data'], errors='coerce')

data_local['Valor R$'] = data_local['Valor R$'].astype(float, errors='ignore')

data_local['à Pagar'] = data_local['à Pagar'].astype(float, errors='ignore')

data_local['Taxa'] = data_local['Taxa'].astype(float, errors='ignore')

data_local['Frete'] = data_local['Frete'].astype(float, errors='ignore')

data_local['Pago'] = data_local['Pago'].astype(int, errors='ignore')

data_local

C:\Users\pedro\AppData\Local\Temp\ipykernel_49192\2125710459.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_local['Data'] = pd.to_datetime(data_local['Data'], errors='coerce')
C:\Users\pedro\AppData\Local\Temp\ipykernel_49192\2125710459.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_local['Valor R$'] = data_local['Valor R$'].astype(float, errors='ignore')
C:\Users\pedro\AppData\Local\Temp\ipykernel_49192\2125710459.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_local['à Pagar'] = data_local['à Pagar'].astype(float, errors='ignore')
C:\Users\pedro\AppData\Local\Temp\ipykernel_49192\2125710459.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_local['Taxa'] = data_local['Taxa'].astype(float, errors='ignore')
C:\Users\pedro\AppData\Local\Temp\ipykernel_49192\2125710459.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_local['Frete'] = data_local['Frete'].astype(float, errors='ignore')
C:\Users\pedro\AppData\Local\Temp\ipykernel_49192\2125710459.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_local['Pago'] = data_local['Pago'].astype(int, errors='ignore')

,Data,Turno,Prato,Valor R$,Pago,à Pagar,Taxa,Frete
0,2020-07-30,Manhã,Liguiça Acebolada + Maionese,12,1.0,0.0,0.0,2.0
1,2020-07-30,Manhã,Carne de Panela + Maionese,12,1.0,0.0,0.0,0.0
2,2020-07-30,Manhã,Frango + Maionese,12,1.0,0.0,0.0,2.0
3,2020-07-30,Manhã,Frango + Maionese,12,1.0,0.0,0.0,0.0
4,2020-07-30,Noite,Frango + Maionese,12,1.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...
2008,2021-10-29,Manhã,strogonoff + batatinha palha,18,1.0,0.0,0.0,0.0
2009,2021-10-29,Manhã,carne moída + legumes + guaracamp,20,1.0,0.0,0.0,0.0
2012,2021-10-30,Manhã,parmê + fritas,18,1.0,0.0,0.0,0.0
2013,2021-10-30,Manhã,2x parmê + fritas,36,1.0,0.0,0.0,0.0
2016,2021-10-31,Manhã,só parmê + fritas,20,1.0,0.0,0.0,0.0

In [9]:
data_local.dtypes

Data        datetime64[ns]
Turno               object
Prato               object
Valor R$            object
Pago               float64
à Pagar            float64
Taxa               float64
Frete              float64
dtype: object

In [10]:
# Changing column names

data_local = data_local.rename(columns={
    'Prato': 'prato', 
    'Turno': 'turno', 
    'Data': 'data_venda', 
    'Valor R$': 'valor_prato', 
    'à Pagar': 'valor_pendente', 
    'Taxa': 'valor_adicional', 
    'Frete': 'valor_frete',
    'Pago': 'pedido_pago'})

data_local

,data_venda,turno,prato,valor_prato,pedido_pago,valor_pendente,valor_adicional,valor_frete
0,2020-07-30,Manhã,Liguiça Acebolada + Maionese,12,1.0,0.0,0.0,2.0
1,2020-07-30,Manhã,Carne de Panela + Maionese,12,1.0,0.0,0.0,0.0
2,2020-07-30,Manhã,Frango + Maionese,12,1.0,0.0,0.0,2.0
3,2020-07-30,Manhã,Frango + Maionese,12,1.0,0.0,0.0,0.0
4,2020-07-30,Noite,Frango + Maionese,12,1.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...
2008,2021-10-29,Manhã,strogonoff + batatinha palha,18,1.0,0.0,0.0,0.0
2009,2021-10-29,Manhã,carne moída + legumes + guaracamp,20,1.0,0.0,0.0,0.0
2012,2021-10-30,Manhã,parmê + fritas,18,1.0,0.0,0.0,0.0
2013,2021-10-30,Manhã,2x parmê + fritas,36,1.0,0.0,0.0,0.0
2016,2021-10-31,Manhã,só parmê + fritas,20,1.0,0.0,0.0,0.0

## Creating dimension tables

Now we will create dimension tables for the data. Our dimension tables will be:

- prato
- turno
- data

### Analisys of 'prato' column before create dim_prato

In [62]:
# Analisys of 'prato'


data_local['prato'].info()

<class 'pandas.core.series.Series'>
Int64Index: 1685 entries, 0 to 2016
Series name: prato
Non-Null Count  Dtype
--------------  -----
1685 non-null   object
dtypes: object(1)
memory usage: 26.3+ KB

In [63]:
data_local['prato'].describe()

count               1685
unique               623
top       parmê + fritas
freq                  77
Name: prato, dtype: object

In [64]:
# We have only 623 unique itens in 'prato', let's see them

unique_pratos = data_local['prato'].unique()

for prato in sorted(unique_pratos):
    print(prato)

 Parmegiana + Purê
 Porção Aipim + Calabresa
 alcatra + fritas e alcatra + purê
 omelete de espinafre + macarrão
 pagou
 parmê + fritas e 2x guaracamp
 parmê + purê
 pavê kitkat + mousse ganache
*****
******
1 Batata Frita
1 Carré
1 Nuggets
1 porção de fritas
1/2 feijão
1/2 fritas extras
1/2 p. aipim frito
1/2 p. fritas
1/2 p. fritas + 2 extras parmegiana + 2 guaracamp
1/2 p. fritas + trufa
1/2 p.fritas + coca 350ml
1/2 porção de fritas
11 quentinhas
1> empanado + maionese + empanado extra + guaracamp
1x - pavê kitkat e 1x - pavê morango
1x- pavê morango + costelinha
2 > a. parmegiana + purê
2 > parmê + fritas
2 Batata Frita
2 Frango Parmegiana
2 Frango Parmegiana
2 Frangos Empanados
2 Frangos a parmegiana
2 Guaracamp
2 Kuat 2l
2 Nuggets
2 Pudim
2 parmê + salada + purê
2> parmegianas
2x - empanado + maionese
2x - parmê + fritas
2x - parmê + fritas e outra salaada
2x - parmê + maionese + salada
2x - pavê de kitkat
2x - porçao calabresa + aipim
2x -> Alcatra + fritas
2x -> Parmegiana + fritas
2x -> empanados + maionese
2x -> parmê + fritas e empanada + salada
2x alcatra + friras
2x alcatra + fritas
2x calabresa + fritas
2x empanado + fritas/maionese e costelinha + maionese
2x empanado + legumes/maionese
2x empanado extra
2x escondidinho
2x extra f. parmegiana
2x f. parmergiana
2x feijão branco + fritas
2x grelhado + purê/legumes
2x parmê + fritas
2x parmê + fritas + kuat
2x parmê + fritas e maionese
2x parmê + fritas e strogonoff + fritas
2x parmê + fritas, grelhado + salada e alcatra + salada
2x parmê + purê
2x parmê + salada
2x pavê de kitkat e 1 de limão
2x- Feijoada
2x- Parmegiana + fritas
2x- alcatra + fritas
2x- parmê + fritas
2x- parmê + maiô
2x-> a.parmê + fritas
2x-> calabresa + fritas
2x-> empanado + fritas
2x-> empanado + maionese
2x-> empanados + fritas e 1 parmê
2x-> parmê + fritas
2x-> parmê + fritas , alcatra + fritas e parmê extra
2x-> parmê + fritas, 1x-> grelhado + maiô, 1x-> empanado + maiô e 1x-> extra empanado
3 Frango Parmegiana
3 Guaracamps
3 alcatras
3> empanado + maionese
3x - grelhado + salada + coca
3x calabresa + maionese
3x costelinha salada/fritas/maionese
3x empanado + fritas
3x frango a parmegiana
3x parmê
3x parmê + fritas e maionese
3x pavês
3x-> empanado + fitas e um com maionese
3x-> parmê + fritas
3x-> parmê + maiô e 1x-> empanado
3x-> parmê + maiô e 2x-> alcatra + fritas
3xparmê + fritas
4x trufas
4x-> quentinhas de empanado + docinhos 2 + coca 2l + fanta 2l
5 Guaracamp
5 Sobremesa
50 salgadinhos
7 nuggets
A. Parmegiana + fritas
A. empanada + fritas
A. paremegiana + fritass
A. parmegiana
A. parmegiana + fritas
A. parmegiana + fritas + coca 350ml
A. parmegiana + maionese
A. parmegiana + maionese + Fanta 350ml
A. parmegiana + maionese + extra alcatra
A. parmegiana +purê
Aipim + Calabresa
Alcatra
Alcatra  + fritas
Alcatra (parmegiana) + Aipim
Alcatra (parmegiana) + Fritas
Alcatra (parmegiana) + Purê
Alcatra + Fritas
Alcatra + Maionese
Alcatra + Purê
Alcatra + fritas
Alcatra + fritas + guaracamp
Alcatra + legumes
Alcatra + legumes -x3
Alcatra + maionese
Alcatra + purê
Alcatra a parmegiana + fritas
Alcatra acebolada + Purê
Alcatra parmegiana + Purê
Alcatra parmegiana + fritas
Alcatra parmegiana + maionese
Alcatra parmegiana + maionese
Alcatra parmegiana + purê
Almôndega + Maionese
Almôndega + Purê
Batata Frita
Bife + Fritas
Bife + Maionese
Bife + Salada
Bife a Parmegiana
Bife a Parmegiana + Batata Frita
Bife a rolé carne + Maionese
Bife a rolé carne + Salada
Bife a rolé carne + fritas
Bife a rolé carne + maionese + fritas
Bife a rolé frango + fritas
Bife de Alcatra + Aipim
Bife de Alcatra + Batata Frita
Bife de Alcatra + Purê
Bife de Alcatra a Parmegiana + Aipim
Bife de Alcatra a Parmegiana + Fritas
Bife à Rolé + Purê
Bolo de pote
Bolonhesa
Bolonhesa
Bolonhesa + Aipim
Bolonhesa + Batata Frita
Bolonhesa + Fritas
Bolonhesa + Maionese
Bolonhesa + Molho branco
Bolonhesa + Purê
Bolonhesa + Salada
Bolonhesa + fritas
Calabresa  + Aipim
Calabresa + Aipim
Calabresa + Fritas
Calabresa + Legumes
Calabresa + Maionese
Calabresa + Ovos
Calabresa + Purê
Calabresa + Salada
Calabresa + fritas
Calabresa + purê
Calabresa + purê + guaracamp
Calabresa +Maionese
Calabresa Acebolada
Calabresas + Aipim
Calabresas + Fritas
Carne Assada + Aipim
Carne Assada + Purê
Carne Assada + Salada
Carne Assada com Molho + Aipim
Carne Assada com Molho + Maionese
Carne Assada com Molho + Salada
Carne Asssada + Aipim
Carne Picadinha + Purê
Carne ao molho + Aipim
Carne assada
Carne assada + Fritas
Carne assada + Maionese
Carne de Panela + Aipim
Carne de Panela + Maionese
Carne de Panela + Purê
Carne de panela + Aipim Frito
Carne de panela + Fritas
Carne de panela + Purê
Carne de panela + Salada
Carne de panela + fritas
Carne de panela + maionese
Carne de panela + purê
Carne de panela + salada verde
Carne moída + Purê
Carre + Linguiça + Frango Empanado + Batata Frita
Carré  + Aipim
Carré + Aipim
Carré + Batata Corada
Carré + Batata Frira
Carré + Batata Frita
Carré + Couve
Carré + Couve + Batata Frita
Carré + Fritas
Carré + Maionese
Carré + Purê
Carré + legumes + Guaracamp
Carré extra
Coca 2,0L
Coca 2,5L
Coca 2L
Coca 350ml
Coca-Cola 2,5L
Coca-Cola 2L
Coca-Cola Lata
Costela + Aipim
Costela + Fritas
Costela + Maionese
Costela + Purê
Costelinha + Aipim
Costelinha + Couve
Costelinha + Fritas
Costelinha + Maionese
Costelinha + Purê
Costelinha + fritas
Costelinha + fritas e parmegiana + maionese
Costelinha Frita
Cubinho Emanado + Batata Frita
Drumet + Aipim
Empanada + maionese
Empanado
Empanado
Empanado (extra)
Empanado (unidade)
Empanado + Aipim
Empanado + Fritas
Empanado + Fritas
Empanado + Maionese
Empanado + Purê
Empanado + Salada
Empanado + fritas
Empanado + fritas
Empanado + maionese
Empanado + purê
Empanado de frango
Empanado+  fritas
Empanado+ Fritas
Empanado+ maionese
Empanado+ purê
Empanadp (só) + maionese
Ensopado
Ensopado + Aipim
Ensopado + Purê
Ensopado de Frango
Ensopado de frango
Estrogonofe + Purê
Estrogonofe de Carne
Estrogonofe de Carne (completo)
Estrogonofe de Carne + Salada de Alface e Tomate
Extras
F. de panela + salada verde
Fanta 2 Lt.
Fanta 2L
Fanta 350ml
Fanta Uva 2L
Fanta Uva 350ml
Fanta guaraná 350ml
Feijoada + Couve
Feijoada + Couve
Feijoada + Couve + Maionese
Feijão + Macarrão + Fritas
Filé de Frango Empanado
Frando ensopado + Salada
Frango +  Batata Frita
Frango + Aipim
Frango + Batata Corada
Frango + Batata Frita
Frango + Maionese
Frango + Salada
Frango Empanado + Aipim
Frango Empanado + Bastante Macarrão
Frango Empanado + Batata Frita
Frango Empanado + Couve-Flor
Frango Empanado + Maionese
Frango Empanado + Purê
Frango Empanado + Salada
Frango Empanado + Salada de Legumes
Frango Grelhado + Salada de Legumes
Frango Parmegiana + Aipim
Frango Parmegiana + Batata Corada
Frango Parmegiana + Batata Frita
Frango Parmegiana + Couve
Frango Parmegiana + Couve-Flor
Frango Parmegiana + Maionese
Frango Parmegiana + Purê
Frango Parmegiana + Purê de batatas
Frango Parmegiana + Salada
Frango Parmegiana + Salada de Alface e Tomate
Frango a parmegiana
Frango ao Molho + Couve-Flor
Frango ao Molho + Salada
Frango empanado + Purê
Frango ensopado + Maionese
Frango ensopado + Salada de Alface e Tomate
Fritas + Calabresa
Fritas + Costela (apenas)
Gorjäoes de Frango + Batata Frita
Grelhado + Fritas
Grelhado + Purê
Grelhado + Salada Verde
Grelhado + fritas
Grelhado + legumes
Grelhado + maionese
Grelhado + purê
Grelhado+ salada verde
Guaracamp
Guaraná 350ml
Kaut 2L
Kuat 2L
Lasanha + Fritas
Liguiça Acebolada + Batata
Liguiça Acebolada + Maionese
Liguiça Acebolada + Purê
Linguiça + Aipim
Linguiça Acebolada + Aipim
Linguiça Acebolada + Maionese
Lombo + Couve
Lombo + Maionese
Lombo + Purê
Lombo + Salada
Macarrão + Grelhado
Macarrão à Bolonhesa + Aipim
Macarrão à Bolonhesa + Purê
Mouse Chocolate c/Maracujá
Mousse
Nuggets + Aipim
Nuggets + Fritas
P. Calabresa + fritas + extra salada
Panqueca
Panqueca + Aipim
Panqueca + Purê
Panqueca + Salada
Panqueca a Bolonhesa
Panqueca a Bolonhesa + Aipim
Parm\~e + fritas e parmê extra
Parmegiana
Parmegiana
Parmegiana (extra)
Parmegiana +  maionese
Parmegiana + Aipim
Parmegiana + Aipim
Parmegiana + Aipim + Salada verde
Parmegiana + Batata Corada
Parmegiana + Coca
Parmegiana + Fritas
Parmegiana + Legumes
Parmegiana + Maionese
Parmegiana + Purê
Parmegiana + Salada
Parmegiana + Salada verde
Parmegiana + aipim
Parmegiana + fritas
Parmegiana + fritas e A. Parmegiana + fritas
Parmegiana + fritas e Calabresa +maionese
Parmegiana + maionese
Parmegiana + purê
Parmegiana + salada verde
Parmegiana +Fritas
Parmegiana de alcatra + Fritas
Parmegiana de frango
Parmê + salada verde
Peixe
Peixe + Batata Corada
Peixe + Maionese
Peixe + Purê
Peixe + Salada
Peixe Empanado + Maionese
Picadinho de Carne + Maionese
Picadinho de Carne + Purê
Porçâo Cubinhos de Frango + Fritas
Porção  Fritas + Calabresa
Porção Aipim
Porção Aipim + Calabresa
Porção Aipim + Calabresa + Purê
Porção Calabresa  + Aipim
Porção Calabresa  +Batata Frita
Porção Calabresa + Aipim
Porção Calabresa + Fritas
Porção Calabresa + Fritas
Porção Calabresa+ Aipim
Porção Cubinho Emanado + Aipim
Porção Frango a Passarinho
Porção Fritas + Calabresa
Porção Salgadinho
Porção Salgadinhos
Porção Sardinha
Porção aipim + calabresa
Porção aipim + calabresa (meia)
Porção aipim + fritas + calabresa
Porção de Fritas
Porção de Salgadinho
Porção de Sardinha
Porção de aipim
Pote Sorvete 2L
Pudim
Refri 2L
Refrigerante 2L
Refrigerante Sabores 1,5L
Sobrecoxa + Batata Corada
Sobrecoxa + Batata Frita
Sobrecoxa + Mainese
Sobrecoxa Assada + Maionese
Sobrecoxa Frita + Maionese
Sprit Lata
Sprit Lata 350ml
Stogronofe de Frango + Salada
Strogonofe de Carne + Salada
Strogonofe de Frango + Salada
Strogonoff
Strogonoff
Strogonoff  + Salada
Strogonoff (puro)
Strogonoff + Aipim
Strogonoff + Fritas
Strogonoff + Purê
Strogonoff + fritas
Strogonoff + purê
Strogonoff Carne
Strogonoff Carne + Aipim Frito
Strogonoff Frango
Strogonoff Frango
Strogonoff Frango + Aipim Frito
Strogonoff carne
Strogonoff de Carne
Strogonoff de Carne  + Aipim
Strogonoff de Carne + Aipim
Strogonoff de carne
Strogonoff de carne
Strogonoff de carne + Batatinha
Strogonoff de carne + Batatinha + Aipim
Strogonoff de carne + Purê
Strogonoff de carne + batatinha
Strogonoff de frango
Strogonoff de frango + Aipim
Strogonoff de frango + batatinha
Strogonoff de frango + batatinha + aipim
Strogonoff frango
Strogonoff frango
Strogonoff frango + Batatinha
Strogonoff frango + Fritas
Strogonoff frango + Salada
Toscana + Aipim
Toscana + Purê
UBER
Uber
a. parmegiana + fritas
a. parmegiana + maionese
a. parmê + fritas
a. parmê + fritas + 1 ref. túlio
a. parmê + fritas + salada
a. parmê + fritas.
a. parmê + maiÔ + alcatra extra
a. parmê + maiô
a. parmê + maiô + 1/2 p. fritas
a. parmê + purê
a. parmê + salada
a. parmê+ maionese
a. parmê+ maionese e f. parmê + fritas
a. parmê+legumes
a.parmegiana + aipim
abóbora + carne seca
acebolado + purê
acumulo
alcatra + aipim
alcatra + fritas
alcatra + legumes
alcatra + legumes e 1 porção de fritas
alcatra + maionese
alcatra + maionese e parmê + fritas
bolo de pote
calabresa + fritas
calabresa + fritas e costelinha + maionese
calabresa + fritas e parmê+fritas
calabresa + maionese
calabresa + purê
calabresa + salada
carne + legumes
carne + salada e parmê +  fritas
carne de panela + maionese
carne moída + fritas
carne moída + legumes + guaracamp
carne moída + maionesa
carne moída + maionese
carne moída + maionese + guaracamp
carne moída + maionese.
carne picadinha + maionese
carré + aipim
carré + fritas
carré + legumes e costela + fritas
carré + maionese
coca 2L
coca 2L
coca 350ml +parmê +fritas
contra-file + fritas
contra-file + fritas x2
costeliha + maionese
costelinha
costelinha + aipim
costelinha + fritas
costelinha + fritas + bolo de amendoim
costelinha + fritas e 2x trufas
costelinha + fritas e guarana 1L
costelinha + maionese
costelinha + maionesw
costelinha + purê
costelinha +legumes
empanado
empanado + fritas
empanado + fritas , strogonoff e coca 2L
empanado + fritas e guaraná 350ml
empanado + fritas e strogonoff + fritas
empanado + legumes e parmê + fritas
empanado + maionese
empanado + maiô
empanado + purê
empanado + purê > extra
empanado e parmê + fritas
empanado+ fritas
f. parmegiana
f. parmê + fritas e a. parmê + fritas
feijão branco + ovo
filé empanado
frango + batata doce
frango a parmegiana
frango assado
fritas
fritas + coca 2L
fígado + alface e tomate
grelhado +  fritas
grelhado + aipim
grelhado + beterraba
grelhado + fritas
grelhado + legumes
grelhado + maionese
grelhado + maiô e fritas extras e grelhado extra
grelhado + purê
grelhado + salada
grelhado + salada e omelete + salada
grelhado + salada, costelinha, parmê + fritas e parmê + salada
kuat 2L
ling.churrasco + aipim
linguiça + maionese
maracrrão + omelete
omelete
omelete + fritas
omelete + fritas + extra omelete
omelete + legumes
omelete de espinafre + fritas
omelete de espinafre + guaracamp
omelete de queijo
omelete extra e omelete + fritas
p. fritas
p. fritas + calabresa
p. fritas + calabresa + aipim
parmegiana
parmegiana + fritas
parmegiana + maionese
parmegiana + salada
parmegiana extra
parmegiana extra x2 + 1/2 p. fritas
parmê + aipim + frango extra
parmê + aipim.
parmê + beterraba
parmê + fritas
parmê + fritas + extra parmê
parmê + fritas , empanado + maiô e parmê + fritas
parmê + fritas e coca 350ml
parmê + fritas e empanado + fritas
parmê + fritas e omelete de queijo
parmê + fritas e strogonoff + fritas
parmê + fritas x2
parmê + fritas x3
parmê + legumes
parmê + maionese
parmê + maiô
parmê + maiô e fanta 350ml
parmê + maiô e grelhado + salada
parmê + purê
parmê + purê
parmê + purê e calabresa + salada
parmê + salada
parmê + salada de legume
parmê + salada verde
parmê e omelete extra
parmê e salada verda
parmê extra + guaracamp
parmê+ fritas
parmê+fritas
parmê+fritas + coca 350ml
parmê+maionese
picadinho + fritas
strogonoff + batatinha palha
strogonoff + fritas
strogonoff + fritas + pavê kitkat
strogonoff + fritas e parmê + fritas
strogonoff + fritas.
strogonoff + maiô
strogonoff de carne + fritas + guaracamp
strogonoff de frango
strogonoff e carré + fritas
strogonoff e parmegiana
só parmê + fritas
trufas x2

In [66]:
# Looks our 'prato' column needs some manipulation

## Extract quantities from 'prato'
data_local['prato'] = data_local['prato'].str.replace('x', '', regex= False)

data_local['quantidade'] = data_local['prato'].str.split().str[0]

data_local['prato'] = data_local['prato'].str.split().str[1:].str.join(' ')

data_local

,data_venda,turno,prato,valor_prato,pedido_pago,valor_pendente,valor_adicional,valor_frete,quantidade
0,2020-07-30,Manhã,Acebolada + Maionese,12,1.0,0.0,0.0,2.0,Liguiça
1,2020-07-30,Manhã,de Panela + Maionese,12,1.0,0.0,0.0,0.0,Carne
2,2020-07-30,Manhã,+ Maionese,12,1.0,0.0,0.0,2.0,Frango
3,2020-07-30,Manhã,+ Maionese,12,1.0,0.0,0.0,0.0,Frango
4,2020-07-30,Noite,+ Maionese,12,1.0,0.0,0.0,2.0,Frango
...,...,...,...,...,...,...,...,...,...
2008,2021-10-29,Manhã,+ batatinha palha,18,1.0,0.0,0.0,0.0,strogonoff
2009,2021-10-29,Manhã,moída + legumes + guaracamp,20,1.0,0.0,0.0,0.0,carne
2012,2021-10-30,Manhã,+ fritas,18,1.0,0.0,0.0,0.0,parmê
2013,2021-10-30,Manhã,parmê + fritas,36,1.0,0.0,0.0,0.0,2
2016,2021-10-31,Manhã,parmê + fritas,20,1.0,0.0,0.0,0.0,só

In [69]:
### Looking for 'quantidade'

unique_quantidade = data_local['quantidade'].unique()

for qtd in unique_quantidade:
    print(qtd)

Liguiça
Carne
Frango
Peie
Panqueca
Strogonofe
Almôndega
Stogronofe
Filé
Carré
Sobrecoa
Batata
Frando
Bife
3
Estrogonofe
Linguiça
2
Nuggets
Ensopado
7
Picadinho
1
Lombo
Carre
5
Calabresa
Macarrão
Porção
UBER
Coca-Cola
Fanta
Pudim
Sprit
Guaracamp
Bolonhesa
Gorjäoes
Cubinho
Drumet
Empanado
Parmegiana
Refrigerante
Porçâo
Guaraná
Alcatra
Kaut
Strogonoff
Coca
Costela
Mouse
filé
Mousse
Aipim
Calabresas
Lasanha
Toscana
Grelhado
Fritas
Refri
50
Costelinha
Feijão
Feijoada
Pote
Kuat
grelhado
parmegiana
fígado
Empanado+
Empanadp
Uber
Bolo
F.
Etras
p.
a.
strogonoff
alcatra
Empanada
A.
******
2-
Grelhado+
P.
1/2
costelinha
4->
calabresa
empanado
parmê
2->
omelete
*****
3->
abóbora
Parm\~e
carne
Parmê
carré
1>
3>
2>
acumulo
maracrrão
contra-file
11
pagou
fritas
f.
picadinho
acebolado
costeliha
trufas
4
parmê+
3parmê
coca
parmê+fritas
ling.churrasco
frango
kuat
pavê
a.parmegiana
1-
empanado+
bolo
linguiça
feijão
parmê+maionese
só